SELECT * FROM customer LIMIT 20;

-- Total Revenue generated by male vs female customers
select gender , SUM(purchase_amount) as revenue
from customer
group by gender;

-- Which customers used a discount but still spent more than the average purchase amount?
select customer_id , purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount)from customer);

-- Top 5 products with the highest average review rating
SELECT item_purchased,
ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY `Average Product Rating` DESC
limit 5;

-- Average Purchase amounts between Standard and Express Shipping
select shipping_type,
ROUND(AVG(purchase_amount),2) AS avg_purchase
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Comparing average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status,
COUNT(customer_id) AS total_customers,
ROUND(AVG(purchase_amount), 2) AS avg_spend,
ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- Which 5 products have the highest percentage of purchases with discount applied?
SELECT item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) * 100, 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Categorize customers as New, Returning, or Loyal based on previous purchases
with customer_type as (
select customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
    ELSE 'Loyal'
    END as customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Top 3 most purchased products within each category
with item_counts as (
select category,
item_purchased,
COUNT(customer_id)as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where Item_rank <=3;

-- Repeat buyers with 5+ purchases who are also subscribers
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

-- Revenue Contribution of each Age group
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

-- Top spending customer in each category
WITH ranked_customers AS (
    SELECT category,
           customer_id,
           SUM(purchase_amount) AS total_spend,
           RANK() OVER(PARTITION BY category ORDER BY SUM(purchase_amount) DESC) AS rnk
    FROM customer
    GROUP BY category, customer_id
)

SELECT *
FROM ranked_customers
WHERE rnk = 1;